name: Build & Deploy to Cloud Run

on:
  push:
    branches:
      - main
      - use-github-actions

permissions:
  contents: read
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ${{ vars.DOCKER_USERNAME }}/${{ github.event.repository.name }}:${{ github.sha }}
            ${{ vars.DOCKER_USERNAME }}/${{ github.event.repository.name }}:latest

      - id: 'auth'
        uses: 'google-github-actions/auth@v2'
        with:
          workload_identity_provider: 'projects/${{ secrets.PROJECT_ID }}/locations/global/workloadIdentityPools/github-actions/providers/my-repo'
          service_account: 'github-actions-update-cloudrun@${{ secrets.GCP_PROJECT_NAME }}.iam.gserviceaccount.com'

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          project_id: ${{ secrets.GCP_PROJECT }}

      - name: Deploy to Cloud Run
        run: |
          gcloud run services update ${{ vars.SERVICE_NAME }} \
            --platform=managed \
            --image=${{ vars.DOCKER_USERNAME }}/${{ github.event.repository.name }}:${{ github.sha }} \
            --region=${{ vars.REGION }}
